/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author lichi
 */
public class CustomerHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerHome.class.getName());

    /**
     * Creates new form CustomerHome
     */
    public CustomerHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCustomerHome_UnregisterFromShop = new javax.swing.JButton();
        btnCustomerHome_BrowseProduct1 = new javax.swing.JButton();
        btnCustomerHome_ViewMyOrder1 = new javax.swing.JButton();
        btnCustomerHome_EditOrders1 = new javax.swing.JButton();
        btnCustomerHome_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCustomerHome_UnregisterFromShop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerHome_UnregisterFromShop.setText("Unregister from Shop");
        btnCustomerHome_UnregisterFromShop.setToolTipText("");

        btnCustomerHome_BrowseProduct1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerHome_BrowseProduct1.setText("Browse Product");

        btnCustomerHome_ViewMyOrder1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerHome_ViewMyOrder1.setText("View Orders");
        btnCustomerHome_ViewMyOrder1.setToolTipText("");

        btnCustomerHome_EditOrders1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerHome_EditOrders1.setText("Edit Details");
        btnCustomerHome_EditOrders1.setToolTipText("");

        btnCustomerHome_Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerHome_Logout.setText("Logout");
        btnCustomerHome_Logout.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCustomerHome_BrowseProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomerHome_EditOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomerHome_ViewMyOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomerHome_UnregisterFromShop, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnCustomerHome_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCustomerHome_BrowseProduct1)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerHome_ViewMyOrder1)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerHome_EditOrders1)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerHome_UnregisterFromShop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCustomerHome_Logout)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerHome_BrowseProduct1;
    private javax.swing.JButton btnCustomerHome_EditOrders1;
    private javax.swing.JButton btnCustomerHome_Logout;
    private javax.swing.JButton btnCustomerHome_UnregisterFromShop;
    private javax.swing.JButton btnCustomerHome_ViewMyOrder1;
    // End of variables declaration//GEN-END:variables
}
