/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import models.DBManager;
import models.Product;

/**
 *
 * @author lichi
 */
public class Shop extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Shop.class.getName());
    private ArrayList<Product> allProducts;
    /**
     * Creates new form Shop
     */
    public Shop() {
        DBManager db = new DBManager();
        allProducts = db.loadProducts();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShop_SelectCategory = new javax.swing.JLabel();
        lblShop_SelectCategory1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSelectProduct = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSelectCategory = new javax.swing.JList<>();
        shopBackToMain = new javax.swing.JButton();
        lblShop_ErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        lblShop_SelectCategory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblShop_SelectCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShop_SelectCategory.setText("SELECT PRODUCT");

        lblShop_SelectCategory1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblShop_SelectCategory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShop_SelectCategory1.setText("SELECT CATEGORY");

        lstSelectProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstSelectProduct);

        lstSelectCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstSelectCategory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Solar Panel", "Heat Pump" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstSelectCategory.addListSelectionListener(this::lstSelectCategoryValueChanged);
        jScrollPane2.setViewportView(lstSelectCategory);

        shopBackToMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shopBackToMain.setText("MAIN");
        shopBackToMain.setActionCommand("MAIN");
        shopBackToMain.addActionListener(this::shopBackToMainActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblShop_SelectCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblShop_SelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(shopBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShop_ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(shopBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShop_SelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShop_SelectCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblShop_ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        shopBackToMain.getAccessibleContext().setAccessibleName("MAIN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstSelectCategoryValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSelectCategoryValueChanged
        // TODO add your handling code here:
        
             
        String productCategorySelected = lstSelectCategory.getSelectedValue();
        System.out.println("clickdd: " + productCategorySelected);
        
        
        //creating new list Model before manupulating the model the form!!!
        DefaultListModel lstProductsModel = new DefaultListModel();
        
        for(Product product : allProducts){
            System.out.println("in for loop, product.getProductType(): " + product.getProductType());
        
            if(product.getProductType().equals(productCategorySelected)){
                lstProductsModel.addElement(product);
            }
        }
        lstSelectProduct.setModel(lstProductsModel);
    }//GEN-LAST:event_lstSelectCategoryValueChanged

    private void shopBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopBackToMainActionPerformed
        // TODO add your handling code here:
        MainMenu mMenu = new MainMenu();
        mMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_shopBackToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Shop().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblShop_ErrorMessage;
    private javax.swing.JLabel lblShop_SelectCategory;
    private javax.swing.JLabel lblShop_SelectCategory1;
    private javax.swing.JList<String> lstSelectCategory;
    private javax.swing.JList<String> lstSelectProduct;
    private javax.swing.JButton shopBackToMain;
    // End of variables declaration//GEN-END:variables
}
