/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.DBManager;
import models.Staff;

/**
 *
 * @author lichi
 */
public class StaffLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffLogin.class.getName());

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStaffLogin = new javax.swing.JButton();
        btnStaffLogin_BackToMain = new javax.swing.JButton();
        lblStaffLogin_UserName = new javax.swing.JLabel();
        lblStaffLogin_Password = new javax.swing.JLabel();
        txtStaffLogin_UserName = new javax.swing.JTextField();
        txtStaffLogin_Password = new javax.swing.JTextField();
        lblStaffLogin_ErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF LOGIN");

        btnStaffLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStaffLogin.setText("LOGIN");
        btnStaffLogin.addActionListener(this::btnStaffLoginActionPerformed);

        btnStaffLogin_BackToMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStaffLogin_BackToMain.setText("MAIN");
        btnStaffLogin_BackToMain.addActionListener(this::btnStaffLogin_BackToMainActionPerformed);

        lblStaffLogin_UserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStaffLogin_UserName.setText("User Name:");

        lblStaffLogin_Password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStaffLogin_Password.setText("Password:");

        txtStaffLogin_UserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtStaffLogin_Password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStaffLogin_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStaffLogin_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaffLogin_UserName)
                            .addComponent(txtStaffLogin_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblStaffLogin_ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnStaffLogin_BackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnStaffLogin_BackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaffLogin_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffLogin_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffLogin_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffLogin_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lblStaffLogin_ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffLogin_BackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLogin_BackToMainActionPerformed
        // TODO add your handling code here:
        MainMenu mMenu = new MainMenu();
        mMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStaffLogin_BackToMainActionPerformed

    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed
        // TODO add your handling code here:
        
//        String username = txtStaffLogin_UserName.getText();
//        String password = txtStaffLogin_Password.getText();

        String username = "DonaldL1";
        String password = "JamesH1";
        
        lblStaffLogin_ErrorMessage.setText("username: "+username+", password : "+password);
     
        DBManager db = new DBManager();
        Staff loggedInStaff = db.staffLogin(username, password);
        lblStaffLogin_ErrorMessage.setText("loggedInStaff,username: "+loggedInStaff.getUserName()+", password : "+loggedInStaff.getPassword());
        
//        if(loggedInStaff!=null){
//            StaffHome sHome = new StaffHome(loggedInStaff);
//            sHome.setVisible(true);
//            this.setVisible(false);
//        }
//        else{
//            lblStaffLogin_ErrorMessage.setText("error, incorrect reg number or manu name");
//        }
    }//GEN-LAST:event_btnStaffLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JButton btnStaffLogin_BackToMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStaffLogin_ErrorMessage;
    private javax.swing.JLabel lblStaffLogin_Password;
    private javax.swing.JLabel lblStaffLogin_UserName;
    private javax.swing.JTextField txtStaffLogin_Password;
    private javax.swing.JTextField txtStaffLogin_UserName;
    // End of variables declaration//GEN-END:variables
}
