/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Staff;

/**
 *
 * @author lichi
 */
public class StaffHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffHome.class.getName());

    /**
     * Creates new form StaffHome
     */
    public StaffHome(Staff s) {
        initComponents();
        lblStaffHome.setText(s.greeting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStaffHome_ModifyProduct = new javax.swing.JButton();
        btnStaffHome_Logout = new javax.swing.JButton();
        btnStaffHome_ViewAllOrders = new javax.swing.JButton();
        lblStaffHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStaffHome_ModifyProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStaffHome_ModifyProduct.setText("Modify Product");
        btnStaffHome_ModifyProduct.addActionListener(this::btnStaffHome_ModifyProductActionPerformed);

        btnStaffHome_Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStaffHome_Logout.setText("Logout");
        btnStaffHome_Logout.setToolTipText("");

        btnStaffHome_ViewAllOrders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStaffHome_ViewAllOrders.setText("View All Orders");
        btnStaffHome_ViewAllOrders.addActionListener(this::btnStaffHome_ViewAllOrdersActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnStaffHome_ViewAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblStaffHome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnStaffHome_ModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btnStaffHome_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnStaffHome_ViewAllOrders)
                .addGap(18, 18, 18)
                .addComponent(lblStaffHome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(btnStaffHome_ModifyProduct)
                    .addGap(188, 188, 188)
                    .addComponent(btnStaffHome_Logout)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffHome_ModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffHome_ModifyProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaffHome_ModifyProductActionPerformed

    private void btnStaffHome_ViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffHome_ViewAllOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaffHome_ViewAllOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new StaffHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStaffHome_Logout;
    private javax.swing.JButton btnStaffHome_ModifyProduct;
    private javax.swing.JButton btnStaffHome_ViewAllOrders;
    private javax.swing.JLabel lblStaffHome;
    // End of variables declaration//GEN-END:variables
}
